kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
#volumeBindingMode: Immediate
#metadata:
#  name: ebs-sc
#provisioner: kubernetes.io/aws-ebs
#parameters:
#  type: io1
#  iopsPerGB: "10"
#  fsType: ext4
