apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
