Name: locust

image:
  repository: greenbirdit/locust
  tag: latest
#  repository: oms1226/locust_eks
#  tag: v0
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  name: master-web
  type: LoadBalancer
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}

# extra volumes, volumeMounts and envs for both worker and master pods
#extraVolumes: []
# extraVolumes:
# - name: mySecretVolume
#   secret:
#     secretName: mySecret
# - name: myConfigMapVolume
#   configMap:
#     name: myConfigMap
#extraVolumeMounts: []
# extraVolumeMounts:
# - name: mySecretVolume
#   mountPath: /locust/secrets/mySecretVolume/
extraVolumeMounts:
  - name: persistent-storage
    mountPath: /efs
extraVolumes:
  - name: persistent-storage
    persistentVolumeClaim:
#      claimName: ebs-claim
      claimName: efs-claim

master:
  config:
#    target-host: https://api-dev.skt-maap-api.com
#    target-host: https://api-stg.skt-maap-api.com
    target-host: http://vpce-0191617aacac59765-8564zunj.vpce-svc-0ea34f30962753e82.ap-northeast-2.vpce.amazonaws.com
    log-file: "/locust-tasks/logfile/tasks.log"
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  nodeSelector: {}
    # kops.k8s.io/instancegroup: master
  tolerations: {}
  # - key: "application"
  #   operator: "Equal"
  #   value: "api"
  #   effect: "NoSchedule"

worker:
  config:

    # Optional parameter to use an existing configmap instead of deploying one with the Chart
    configmapName: locust-worker-configs

    # all files from specified configmap (or tasks folder) are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/tasks_maap.py"
  replicaCount: 100
  resources:
    limits:
      cpu: 100m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  nodeSelector: {}
    # kops.k8s.io/instancegroup: worker
  tolerations: {}
  # - key: "application"
  #   operator: "Equal"
  #   value: "api"
  #   effect: "NoSchedule"
